config/routes.rb
Rails.application.routes.draw do
  get 'rooms/index'
  post 'rooms/show'
  get 'rooms/show'
  get 'choices/new/:id', to: 'choices#new'
  get 'choices/new/:id/:count', to: 'choices#new'
  post 'choises/create/:count', to: 'choises#create'
  get 'questions/new/:id', to: 'questions#new'
  get 'questions/show/:id', to: 'questions#show'
  resources :choices
  resources :questions
  resources :genres
  resources :users
  devise_for :accounts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
    belongs_to :user
    belongs_to :genre
    has_many :choice

    validates :title, presence: {message:'は、必須項目です。'}
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  layout 'questions'
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.page(params[:page]).order('created_at desc')
    @genres = Genre.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @choices = Choice.where 'question_id = ?', @question.id
    @genres = Genre.all
  end

  # GET /questions/new
  def new
    @question = Question.new
    @question.user_id = params[:id]
    @genres = Genre.all
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to '/choices/new/' + @question.id.to_s }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:title, :memo, :genre_id, :user_id)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_area :title %>
  </div>

  <div class="field">
    <%= form.label :memo %>
    <%= form.text_area :memo %>
  </div>

  <div class="field">
    genre<br>
    <% @genres.each do |genre| %>
      <%= form.radio_button :genre_id, genre.id %><%= genre.genrename %>
    <% end %>
  </div>

  <%= form.hidden_field :user_id %>
  

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<h1>新着クイズ一覧</h1>

<ul>
  <% @questions.each do |question| %>
    <li class="qarea">
      <div>
        <a class="link" href="/questions/show/<%= question.id %>"><%= question.title %></a><br>
        <a class="inlink" href="/questions/genre/<%= question.genre.id %>"><%= question.genre.genrename %></a><br>
        <a class="inlink" href="/users/<%= question.user.id %>"><%= question.user.name %></a>
      </div>
    </li>

  <% end %>
</ul>

app/views/questions/new.html.erb
<h1>新しいクイズを作成</h1>

<%= render 'form', question: @question %>



<%= link_to 'Back', '/users' %>

app/views/questions/show.html.erb
<p><span class="show_title"><%= @question.title %></span>
<span class="show_nav">ジャンル:<%= @question.genre.genrename %>  作成者:<%= @question.user.name %>  作成日:<%= @question.created_at %></apan>
</p>

<p>作者コメント「<%= @question.memo %>」</p>

<div class="slider">
  <div class="slideSet">
    <% count = 1 %>
    <% array = [] %>
    <% @choices.each do |choice| %>
      <div class="slide" id="slide<%= count.to_s %>">
        <p class="choicecount"><%= count.to_s %>問目</p>
        <p class="choicetext"><%= choice.text %></p>
        <% array[0] = "<input type='button' value='" + choice.correct + "' onclick='correct(" + count.to_s + ")'>"  %>
        <% if choice.dummya.length > 0 then %>
          <% array[1] = "<input type='button' value='" + choice.dummya + "' onclick='incorrect(" + count.to_s + ")'>"  %>
        <% end %>
        <% if choice.dummyb.length > 0 then %>
          <% array[2] = "<input type='button' value='" + choice.dummyb + "' onclick='incorrect(" + count.to_s + ")'>"  %>
        <% end %>
        <% if choice.dummyc.length > 0 then %>
          <% array[3] = "<input type='button' value='" + choice.dummyc + "' onclick='incorrect(" + count.to_s + ")'>"  %>
        <% end %>
        <div class="choice"> 
          <% array.shuffle.each do |obj| %>
            <%= obj.html_safe %><br>
          <% end %>
          <% array.clear %>
          <br>
        </div>
        <% if choice.hint.length > 0 then %>
            <input type="button" value="ヒント" onclick="hint(<%= count.to_s %>)">
            <span class="hintarea" id="hintarea<%= count.to_s %>"><%= choice.hint %></span>
        <% end %>
      </div>
      <div class="slide" id="slideans<%= count.to_s %>">
        <h2 id="ans<%= count.to_s %>"></h2>
        <p>答え:<%= choice.correct %></p>
        <p><%= choice.comment %></p>
        <button class="next">次へ</button>
      </div>
      <% count += 1 %>
    <% end %>
    <div class="slide">
      <h2>終了!</h2>
      <p>あなたの得点は・・・</p>
      <h1 id="score"></h1>
    </div>
  </div>
</div>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>

<script>
  var slideWidth = $('.slide').outerWidth(); // .slideの幅を取得して代入
  var slideNum = $('.slide').length;
  var slideSetWidth = slideWidth * slideNum; // .slideの幅×数で求めた値を代入
  console.log(slideNum);
  $('.slideSet').css('width', slideSetWidth);
  $('.hintarea').hide();
  
  var slideCurrent = 0;
  var correctCounter = 0;
  var quiznum = (slideNum - 1)/2;
    
  var sliding = function(){
    $('.slideSet').animate({
      left: slideCurrent * -slideWidth
    });
  }

  var score = function(){
    $('#score').text(correctCounter + "/" + quiznum + "点！");
  }
  
  $('.slider-prev').click(function(){
    slideCurrent--;
    sliding();
  });
  
  $('.next').click(function(){
    slideCurrent++;
    sliding();
  });
  
  
  function correct(num) {
    $('#ans' + num).text('正解')
    slideCurrent++;
    correctCounter++;
    score();
    sliding();
  }

  function incorrect(num) {
    $('#ans' + num).text('不正解')
    slideCurrent++;
    score();
    sliding();
  }

  function hint(num) {
    $('#hintarea' + num).show();
  }
  
</script>