config/routes.rb
Rails.application.routes.draw do
  get 'rooms/index'
  post 'rooms/show'
  get 'rooms/show'
  get 'choices/new/:id', to: 'choices#new'
  get 'choices/new/:id/:count', to: 'choices#new'
  post 'choises/create/:count', to: 'choises#create'
  get 'questions/new/:id', to: 'questions#new'
  get 'questions/show/:id', to: 'questions#show'
  resources :choices
  resources :questions
  resources :genres
  resources :users
  devise_for :accounts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/choice.rb
class Choice < ApplicationRecord
    belongs_to :question

    validates :text, :correct, presence: {message:'は、必須項目です。'}
end

app/controllers/choices_controller.rb
class ChoicesController < ApplicationController
  before_action :set_choice, only: [:show, :edit, :update, :destroy]

  # GET /choices
  # GET /choices.json
  def index
    @choices = Choice.all
  end

  # GET /choices/1
  # GET /choices/1.json
  def show
  end

  # GET /choices/new
  def new
    @choice = Choice.new
    @choice.question_id = params[:id]
    @question = Question.find params[:id]
    if params[:count] != nil then
      @count = params[:count]
    else
      @count = 1
    end
  end

  # GET /choices/1/edit
  def edit
  end

  # POST /choices
  # POST /choices.json
  def create
    @choice = Choice.new(choice_params)
    @count = params[:count].to_i + 1
  
    respond_to do |format|
      if @choice.save
        if @count <= 10
          format.html { redirect_to '/choices/new/' + @choice.question_id.to_s + '/' + @count.to_s }
        else
          format.html { redirect_to '/users' }
        end
        format.json { render :show, status: :created, location: @choice }
      else
        format.html { render :new }
        format.json { render json: @choice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /choices/1
  # PATCH/PUT /choices/1.json
  def update
    respond_to do |format|
      if @choice.update(choice_params)
        format.html { redirect_to @choice, notice: 'Choice was successfully updated.' }
        format.json { render :show, status: :ok, location: @choice }
      else
        format.html { render :edit }
        format.json { render json: @choice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /choices/1
  # DELETE /choices/1.json
  def destroy
    @choice.destroy
    respond_to do |format|
      format.html { redirect_to choices_url, notice: 'Choice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_choice
      @choice = Choice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def choice_params
      params.require(:choice).permit(:text, :correct, :dummya, :dummyb, :dummyc, :hint, :comment, :question_id)
    end
end

app/helpers/choices_helper.rb
module ChoicesHelper
end

app/views/choices/_form.html.erb
<%= form_for(choice, url:{controller: 'choices', action: 'create',count:@count}) do |form| %>
  <% if choice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(choice.errors.count, "error") %> prohibited this choice from being saved:</h2>

      <ul>
      <% choice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text %>
  </div>

  <div class="field">
    <%= form.label :correct %>
    <%= form.text_area :correct %>
  </div>

  <div class="field">
    <%= form.label :dummya %>
    <%= form.text_area :dummya %>
  </div>

  <div class="field">
    <%= form.label :dummyb %>
    <%= form.text_area :dummyb %>
  </div>

  <div class="field">
    <%= form.label :dummyc %>
    <%= form.text_area :dummyc %>
  </div>

  <div class="field">
    <%= form.label :hint %>
    <%= form.text_area :hint %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment %>
  </div>

  <div class="field">
    <%= form.label :question_id %>
    <%= form.number_field :question_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/choices/edit.html.erb
<h1>Editing Choice</h1>

<%= render 'form', choice: @choice %>

<%= link_to 'Show', @choice %> |
<%= link_to 'Back', choices_path %>

app/views/choices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Choices</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th>Correct</th>
      <th>Dummya</th>
      <th>Dummyb</th>
      <th>Dummyc</th>
      <th>Hint</th>
      <th>Comment</th>
      <th>Question</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @choices.each do |choice| %>
      <tr>
        <td><%= choice.text %></td>
        <td><%= choice.correct %></td>
        <td><%= choice.dummya %></td>
        <td><%= choice.dummyb %></td>
        <td><%= choice.dummyc %></td>
        <td><%= choice.hint %></td>
        <td><%= choice.comment %></td>
        <td><%= choice.question_id %></td>
        <td><%= link_to 'Show', choice %></td>
        <td><%= link_to 'Edit', edit_choice_path(choice) %></td>
        <td><%= link_to 'Destroy', choice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Choice', new_choice_path %>

app/views/choices/new.html.erb
<h1><%= @question.title %> <%= @count %>問目</h1>
<% if @count.to_i > 1 then %>
    <p><a href="/users"><%= @count.to_i - 1 %>問で終わる</a></p>
<% end %>

<%= render 'form', choice: @choice %>

app/views/choices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @choice.text %>
</p>

<p>
  <strong>Correct:</strong>
  <%= @choice.correct %>
</p>

<p>
  <strong>Dummya:</strong>
  <%= @choice.dummya %>
</p>

<p>
  <strong>Dummyb:</strong>
  <%= @choice.dummyb %>
</p>

<p>
  <strong>Dummyc:</strong>
  <%= @choice.dummyc %>
</p>

<p>
  <strong>Hint:</strong>
  <%= @choice.hint %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @choice.comment %>
</p>

<p>
  <strong>Question:</strong>
  <%= @choice.question_id %>
</p>

<%= link_to 'Edit', edit_choice_path(@choice) %> |
<%= link_to 'Back', choices_path %>