config/routes.rb
Rails.application.routes.draw do
  get 'rooms/index'
  post 'rooms/show'
  get 'rooms/show'
  get 'choices/new/:id', to: 'choices#new'
  get 'choices/new/:id/:count', to: 'choices#new'
  post 'choises/create/:count', to: 'choises#create'
  get 'questions/new/:id', to: 'questions#new'
  get 'questions/show/:id', to: 'questions#show'
  resources :choices
  resources :questions
  resources :genres
  resources :users
  devise_for :accounts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    belongs_to :account
    has_many :question

    validates :name, presence: {message:'は、必須項目です。'}
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_account!

  # GET /users
  # GET /users.json
  def index
    users = User.where 'account_id == ?', current_account.id
    if users[0] == nil then
      user = User.new
      user.account_id = current_account.id
      user.name = '<<no name>>'
      user.save 
      users = User.where 'account_id == ?', current_account.id
    end
    @users = users[0]
    @quiz = Question.where 'user_id == ?', @users.id
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @quiz = Question.where 'user_id == ?', @user.id
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to '/users'}
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :account_id, :memo)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_area :name %>
  </div>


    <%= form.hidden_field :account_id %>


  <div class="field">
    <%= form.label :memo %>
    <%= form.text_area :memo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>ユーザー設定</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>「<%= @users.name%>」さんのホーム</h1>
<div><%= link_to "ログアウト", destroy_account_session_path(), method: :delete %></div>

<table>
  <tr>
    <th>名前</th><td><%= @users.name %></td>
  </tr>
  <tr>
    <th>ID</th><td><%= @users.account_id %></td>
  </tr>
  <tr>
    <th>コメント</th><td><%= @users.memo %></td>
  </tr>
  <tr>
    <th></th><td><%= link_to 'Edit', edit_user_path(@users) %></td>
  </tr>
</table>

<hr>
<a href="/questions/new/<%= @users.account_id %>">クイズを作る</a><br>
<a href="/questions">戻る</a>
<hr>
<p>「<%= @users.name%>」さんが作ったクイズ</p>
<ul>
<% @quiz.each do |quiz| %>
  <li><a href="/questions/show/<%= quiz.id %>"><%= quiz.title %></a></li>
<% end %>
</ul>
  

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h1>「<%= @user.name%>」さんのホーム</h1>

<table>
  <tr>
    <th>名前</th><td><%= @user.name %></td>
  </tr>
  <tr>
    <th>ID</th><td><%= @user.account_id %></td>
  </tr>
  <tr>
    <th>コメント</th><td><%= @user.memo %></td>
  </tr>
</table>

<hr>
<a href="/questions">戻る</a>
<hr>
<p>「<%= @user.name%>」さんが作ったクイズ</p>
<ul>
<% @quiz.each do |quiz| %>
  <li><a href="/questions/show/<%= quiz.id %>"><%= quiz.title %></a></li>
<% end %>
</ul>